/*
Copyright ArxanChain Ltd. 2020 All Rights Reserved.

SPDX-License-Identifier: Apache-2.0
*/

package utils

import (
	"crypto/rand"
	"fmt"
	"io"
	"regexp"
)

const (
	phoneReg = `^(13[0-9]|14[579]|16[2567]|15[01235-9]|1[78][0-9])\d{8}$`
)

// CheckPhone return phone is valid
func CheckPhone(phone string) bool {
	reg := regexp.MustCompile(phoneReg)
	return reg.MatchString(phone)
}

// CheckPassword check password length and illegal characters
func CheckPassword(pwd string) bool {
	//长度8-16位,必须包含大小写字母和数字
	if len(pwd) < 8 || len(pwd) > 16 {
		return false
	}
	r1 := regexp.MustCompile("[a-z]")
	r2 := regexp.MustCompile("[A-Z]")
	r3 := regexp.MustCompile("[0-9]")
	if r1.MatchString(pwd) && r2.MatchString(pwd) && r3.MatchString(pwd) {
		return true
	}
	return false
}

// GenerateUUID returns a UUID based on RFC 4122
func GenerateUUID() string {
	uuid := GenerateBytesUUID()
	return uuidBytesToStr(uuid)
}

// GenerateBytesUUID returns a UUID based on RFC 4122 returning the generated bytes
func GenerateBytesUUID() []byte {
	uuid := make([]byte, 16)
	_, err := io.ReadFull(rand.Reader, uuid)
	if err != nil {
		panic(fmt.Sprintf("Error generating UUID: %s", err))
	}

	// variant bits; see section 4.1.1
	uuid[8] = uuid[8]&^0xc0 | 0x80

	// version 4 (pseudo-random); see section 4.1.3
	uuid[6] = uuid[6]&^0xf0 | 0x40

	return uuid
}

func uuidBytesToStr(uuid []byte) string {
	return fmt.Sprintf("%x", uuid)
}
