name: Go
on:
  pull_request:
    branches:
    - master
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.12
      uses: actions/setup-go@v1
      with:
        go-version: 1.12
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Get dependencies
      run: |
        make mod

    - name: Check fmt
      run: make fmt-check vet
      
    - name: Build Binary
      run: make default
      
    - name: Run Test
      run: make test
